# GHOST News Engine Configuration
# Конфигурация для улучшенного News Engine

database:
  path: "ghost_news.db"
  type: "sqlite"

sources:
  newsapi:
    enabled: true
    api_key: "${NEWS_API_KEY}"  # Берется из .env
    base_url: "https://newsapi.org/v2"
    keywords: 
      - "crypto"
      - "bitcoin" 
      - "ethereum"
      - "blockchain"
      - "defi"
      - "nft"
      - "binance"
      - "coinbase"
    interval: 60

  twitter:
    enabled: true  # Включен, если есть токен
    bearer_token: "${TWITTER_BEARER_TOKEN}"  # Берется из .env
    keywords:
      - "#crypto"
      - "#bitcoin"
      - "#ethereum"
      - "#defi"
    interval: 30

  cryptocompare:
    enabled: true
    api_key: "${CRYPTOCOMPARE_API_KEY}"  # Берется из .env
    base_url: "https://min-api.cryptocompare.com/data"
    interval: 120

  alphavantage:
    enabled: true
    api_key: "${ALPHA_VANTAGE_API_KEY}"  # Берется из .env
    base_url: "https://www.alphavantage.co/query"
    interval: 300

  reuters:
    enabled: true
    api_key: "${REUTERS_API_KEY}"  # Берется из .env
    base_url: "https://api.reuters.com/v1"
    interval: 600

  bloomberg:
    enabled: true
    api_key: "${BLOOMBERG_API_KEY}"  # Берется из .env
    base_url: "https://api.bloomberg.com/v1"
    interval: 600

  cnbc:
    enabled: true
    api_key: "${CNBC_API_KEY}"  # Берется из .env
    base_url: "https://api.cnbc.com/v1"
    interval: 600

  techcrunch:
    enabled: true
    api_key: "${TECHCRUNCH_API_KEY}"  # Берется из .env
    base_url: "https://api.techcrunch.com/v1"
    interval: 900

  theverge:
    enabled: true
    api_key: "${THEVERGE_API_KEY}"  # Берется из .env
    base_url: "https://api.theverge.com/v1"
    interval: 900

  sec:
    enabled: true
    api_key: "${SEC_API_KEY}"  # Берется из .env
    base_url: "https://api.sec.gov"
    interval: 1800

  cftc:
    enabled: true
    api_key: "${CFTC_API_KEY}"  # Берется из .env
    base_url: "https://api.cftc.gov/v1"
    interval: 1800

  coingecko:
    enabled: true
    api_key: "${COINGECKO_API_KEY}"  # Берется из .env
    base_url: "https://api.coingecko.com/api/v3"
    interval: 300

  binance:
    enabled: true
    api_key: "${BINANCE_API_KEY}"  # Берется из .env
    secret_key: "${BINANCE_SECRET_KEY}"  # Берется из .env
    base_url: "https://api.binance.com/api/v3"
    interval: 1

  coinbase:
    enabled: true
    api_key: "${COINBASE_API_KEY}"  # Берется из .env
    secret_key: "${COINBASE_SECRET_KEY}"  # Берется из .env
    base_url: "https://api.coinbase.com/v2"
    interval: 1

  reddit:
    enabled: true
    client_id: "${REDDIT_CLIENT_ID}"  # Берется из .env
    client_secret: "${REDDIT_CLIENT_SECRET}"  # Берется из .env
    user_agent: "${REDDIT_USER_AGENT}"  # Берется из .env
    base_url: "https://oauth.reddit.com"
    interval: 600

  regulatory:
    enabled: true
    sources:
      - "SEC"
      - "CFTC"
      - "FED"
    interval: 360  # Каждые 6 часов

trust_scores:
  # Официальные источники
  "Reuters": 0.95
  "Bloomberg": 0.90
  "Associated Press": 0.92
  "Financial Times": 0.88
  
  # Крипто-медиа
  "CoinTelegraph": 0.75
  "CoinDesk": 0.80
  "CryptoNews": 0.65
  "Decrypt": 0.70
  
  # Социальные сети
  "elonmusk (Twitter)": 0.60
  "VitalikButerin (Twitter)": 0.75
  
  # По умолчанию
  "*": 0.50

influence:
  tweet:
    weight_followers: 0.6
    weight_retweets: 0.3
    weight_likes: 0.1
    min_followers: 1000
  
  news:
    base_influence:
      "Reuters": 0.9
      "Bloomberg": 0.9
      "Associated Press": 0.85
      "Financial Times": 0.85
      "CoinTelegraph": 0.7
      "CoinDesk": 0.75
      "CryptoNews": 0.6
      "UnknownBlog": 0.4

sentiment:
  method: "vader"  # vader, textblob, custom
  thresholds:
    positive: 0.1
    negative: -0.1
    neutral: 0.05
  
  # Настройки для финансовых новостей
  financial_keywords:
    positive: ["bullish", "surge", "rally", "gain", "profit", "growth"]
    negative: ["bearish", "crash", "drop", "loss", "decline", "sell-off"]

urgency:
  decay_hours: 24
  instant_keywords:
    - "BREAKING"
    - "URGENT"
    - "CRASH"
    - "EXPLOSION"
    - "HACK"
    - "SECURITY"
    - "REGULATION"
    - "BAN"
  
  # Множители срочности для разных типов
  multipliers:
    regulatory: 1.5
    breaking_news: 2.0
    market_crash: 2.5

processing:
  batch_size: "${BATCH_SIZE}"  # Берется из .env
  max_retries: "${MAX_RETRIES}"  # Берется из .env
  timeout: "${REQUEST_TIMEOUT}"  # Берется из .env
  max_concurrent_requests: "${MAX_CONCURRENT_REQUESTS}"  # Берется из .env
  
  # Настройки для важных новостей
  important_thresholds:
    influence: 0.7
    sentiment_abs: 0.5
    urgency: 0.8
    source_trust: 0.8

# Настройки уведомлений
notifications:
  enabled: true
  important_news: true
  error_alerts: true
  
  # Каналы уведомлений
  channels:
    telegram: 
      enabled: true
      bot_token: "${TELEGRAM_BOT_TOKEN}"  # Берется из .env
      chat_id: "${TELEGRAM_CHAT_ID}"  # Берется из .env
    email: 
      enabled: true
      smtp_server: "${SMTP_SERVER}"  # Берется из .env
      smtp_port: "${SMTP_PORT}"  # Берется из .env
      user: "${EMAIL_USER}"  # Берется из .env
      password: "${EMAIL_PASSWORD}"  # Берется из .env
    webhook: 
      enabled: true
      url: "${WEBHOOK_URL}"  # Берется из .env

# Настройки мониторинга
monitoring:
  health_check_interval: 60
  log_level: "${LOG_LEVEL}"  # Берется из .env
  metrics_enabled: true
  log_file: "${LOG_FILE}"  # Берется из .env
  
  # Метрики для отслеживания
  metrics:
    - "news_count_per_hour"
    - "average_sentiment"
    - "important_news_count"
    - "source_trust_distribution"
