database:
  path: ghost_news.db
  type: sqlite
influence:
  news:
    base_influence:
      Associated Press: 0.85
      Bloomberg: 0.9
      CoinDesk: 0.75
      CoinTelegraph: 0.7
      CryptoNews: 0.6
      Financial Times: 0.85
      Reuters: 0.9
      UnknownBlog: 0.4
  tweet:
    min_followers: 1000
    weight_followers: 0.6
    weight_likes: 0.1
    weight_retweets: 0.3
monitoring:
  health_check_interval: 60
  log_file: ${LOG_FILE}
  log_level: ${LOG_LEVEL}
  metrics:
  - news_count_per_hour
  - average_sentiment
  - important_news_count
  - source_trust_distribution
  metrics_enabled: true
notifications:
  channels:
    email:
      enabled: true
      password: ${EMAIL_PASSWORD}
      smtp_port: ${SMTP_PORT}
      smtp_server: ${SMTP_SERVER}
      user: ${EMAIL_USER}
    telegram:
      bot_token: ${TELEGRAM_BOT_TOKEN}
      chat_id: ${TELEGRAM_CHAT_ID}
      enabled: true
    webhook:
      enabled: true
      url: ${WEBHOOK_URL}
  enabled: true
  error_alerts: true
  important_news: true
processing:
  batch_size: ${BATCH_SIZE}
  important_thresholds:
    influence: 0.7
    sentiment_abs: 0.5
    source_trust: 0.8
    urgency: 0.8
  max_concurrent_requests: ${MAX_CONCURRENT_REQUESTS}
  max_retries: ${MAX_RETRIES}
  timeout: ${REQUEST_TIMEOUT}
sentiment:
  financial_keywords:
    negative:
    - bearish
    - crash
    - drop
    - loss
    - decline
    - sell-off
    positive:
    - bullish
    - surge
    - rally
    - gain
    - profit
    - growth
  method: vader
  thresholds:
    negative: -0.1
    neutral: 0.05
    positive: 0.1
sources:
  alphavantage:
    api_key: ${ALPHA_VANTAGE_API_KEY}
    base_url: https://www.alphavantage.co/query
    enabled: true
    interval: 300
  binance:
    api_key: ${BINANCE_API_KEY}
    base_url: https://api.binance.com/api/v3
    enabled: true
    interval: 1
    secret_key: ${BINANCE_SECRET_KEY}
  bloomberg:
    api_key: ${BLOOMBERG_API_KEY}
    base_url: https://api.bloomberg.com/v1
    enabled: true
    interval: 600
  cftc:
    api_key: ${CFTC_API_KEY}
    base_url: https://api.cftc.gov/v1
    enabled: true
    interval: 1800
  cnbc:
    api_key: ${CNBC_API_KEY}
    base_url: https://api.cnbc.com/v1
    enabled: true
    interval: 600
  coinbase:
    api_key: ${COINBASE_API_KEY}
    base_url: https://api.coinbase.com/v2
    enabled: true
    interval: 1
    secret_key: ${COINBASE_SECRET_KEY}
  coingecko:
    api_key: ${COINGECKO_API_KEY}
    base_url: https://api.coingecko.com/api/v3
    enabled: true
    interval: 300
  cryptocompare:
    api_key: ${CRYPTOCOMPARE_API_KEY}
    base_url: https://min-api.cryptocompare.com/data
    enabled: true
    interval: 120
  newsapi:
    api_key: ${NEWS_API_KEY}
    base_url: https://newsapi.org/v2
    enabled: true
    interval: 60
    keywords:
    - crypto
    - bitcoin
    - ethereum
    - blockchain
    - defi
    - nft
    - binance
    - coinbase
  reddit:
    base_url: https://oauth.reddit.com
    client_id: ${REDDIT_CLIENT_ID}
    client_secret: ${REDDIT_CLIENT_SECRET}
    enabled: true
    interval: 600
    user_agent: ${REDDIT_USER_AGENT}
  regulatory:
    enabled: true
    interval: 360
    sources:
    - SEC
    - CFTC
    - FED
  reuters:
    api_key: ${REUTERS_API_KEY}
    base_url: https://api.reuters.com/v1
    enabled: true
    interval: 600
  sec:
    api_key: ${SEC_API_KEY}
    base_url: https://api.sec.gov
    enabled: true
    interval: 1800
  techcrunch:
    api_key: ${TECHCRUNCH_API_KEY}
    base_url: https://api.techcrunch.com/v1
    enabled: true
    interval: 900
  theverge:
    api_key: ${THEVERGE_API_KEY}
    base_url: https://api.theverge.com/v1
    enabled: true
    interval: 900
  twitter:
    bearer_token: ${TWITTER_BEARER_TOKEN}
    enabled: true
    interval: 30
    keywords:
    - '#crypto'
    - '#bitcoin'
    - '#ethereum'
    - '#defi'
trust_scores:
  '*': 0.5
  Associated Press: 0.92
  Bloomberg: 0.9
  CoinDesk: 0.8
  CoinTelegraph: 0.75
  CryptoNews: 0.65
  Decrypt: 0.7
  Financial Times: 0.88
  Reuters: 0.95
  VitalikButerin (Twitter): 0.75
  elonmusk (Twitter): 0.6
urgency:
  decay_hours: 24
  instant_keywords:
  - BREAKING
  - URGENT
  - CRASH
  - EXPLOSION
  - HACK
  - SECURITY
  - REGULATION
  - BAN
  multipliers:
    breaking_news: 2.0
    market_crash: 2.5
    regulatory: 1.5
