[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python telegram_parsers/whales_guide_listener.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "whales-telegram-parser"
source = "."

[services.variables]
PYTHON_VERSION = "3.11"
PORT = "8000"

[[services]]
name = "news-engine"
source = "."
startCommand = "python news_engine/enhanced_news_engine.py"

[[services]]
name = "signal-processor"
source = "."
startCommand = "python signals/signal_orchestrator.py"
