# Render.com deployment configuration for GHOST All-in-One Engine
services:
  # Unified Service for All GHOST Engines
  - type: web
    name: ghost-all-engines
    env: python
    repo: https://github.com/sacraldj/ghost.git
    branch: main
    buildCommand: "pip install -r requirements.txt && pip install -r telegram_parsers/requirements.txt"
    startCommand: "python3 start_all.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        value: "8000"
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_PHONE
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false