# GHOST Telegram Channels Configuration
# Список каналов для мониторинга сигналов

channels:
  # Пример канала для торговых сигналов
  - id: -1001234567890  # Замените на реальный chat_id канала
    name: "Trading Signals Channel"
    type: "trade"
    trigger: "LONG"  # Ключевое слово для активации
    
  # Пример канала для новостей
  - id: -1001111111111  # Замените на реальный chat_id канала  
    name: "Crypto News Channel"
    type: "news"
    trigger: null  # Обрабатывать все сообщения
    
  # Канал для тестирования (публичный)
  - id: -1001369125713  # Пример публичного канала
    name: "Test Channel"
    type: "test"
    trigger: null

# Как получить chat_id канала:
# 1. Добавьте бота @userinfobot в канал
# 2. Отправьте любое сообщение
# 3. Бот покажет chat_id канала
# 4. Для приватных каналов chat_id обычно отрицательный

# Типы каналов:
# - test: тестовый режим, все сообщения
# - trade: торговые сигналы, только с триггерами
# - news: новости, все сообщения
# - universal: универсальный, все сообщения
