check_interval: 60
connection_params:
  api_hash: YOUR_API_HASH
  api_id: YOUR_API_ID
  channel_id: '-1001234567892'
  phone: YOUR_PHONE
created_at: '2025-08-13T21:32:15.412898'
description: Premium signals group
filters:
  keywords_include:
  - 🔥
  - 💎
  - VIP
  min_targets: 2
last_error: null
last_success: null
max_retries: 3
name: VIP Private Signals
parser_config:
  confidence_threshold: 0.9
  premium_features: true
parser_type: vip_signals_parser
priority: 5
retry_delay: 300
source_id: vip_private_group
source_type: telegram_group
status: active
updated_at: '2025-08-13T21:32:15.412899'
